Library/Models/Livro.cs
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
    public class Livro
    {
        public int Id { get; set; }
        [Display(Name = "Título")]
        public string Titulo { get; set; }
        [Display(Name = "Edição")]
        public int Edicao { get; set; }
        public int Ano { get; set; }
        public virtual Editora Editora { get; set; }
        [Display(Name = "Editora")]
        public int EditoraId { get; set; }
        [Display(Name = "Autor")]
        public virtual List<LivroAutor> LivroAutor { get; set; }
        [Display(Name = "Assunto")]
        public virtual List<LivroAssunto> LivroAssunto { get; set; }
        public byte[] Dados { get; set; }
        public string ContentType { get; set; }
        public virtual IdentityUser IdentityUser { get; set; }
        public string IdentityUserId { get; set; }

        public Livro()
        {

        }
    }
}

Library/Models/ViewModels/Livros.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Library.Models.ViewModels
{
    public class Livros
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public List<string> Autores { get; set; }
        public int Edicao { get; set; }
        public int Ano { get; set; }
        public string Editora { get; set; }
        public List<string> Assuntos { get; set; }
        public FileStreamResult Foto { get; set; }

        public Livros()
        {

        }
    }
}

Library/Controllers/LivrosController.cs
using Library.Data;
using Library.Models;
using Library.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Controllers
{
    [Authorize]
    public class LivrosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LivrosController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("livros/index")]
        // GET: Livros
        public async Task<IActionResult> Index(int? busca, string search, string order)
        {
            var user = User.Identity.Name;

            var userId = (from c in _context.Users
                          where c.UserName == user
                          select c.Id).FirstOrDefault();

            List<Livros> Livro = new List<Livros>();

            List<SelectListItem> itens = new List<SelectListItem>();
            SelectListItem item1 = new SelectListItem() { Text = "Livro", Value = "1", Selected = true };
            SelectListItem item2 = new SelectListItem() { Text = "Autor", Value = "2", Selected = false };
            SelectListItem item3 = new SelectListItem() { Text = "Editora", Value = "3", Selected = false };
            itens.Add(item1);
            itens.Add(item2);
            itens.Add(item3);

            ViewBag.Busca = itens;
            ViewBag.Titulo = order == "Titulo" ? "Titulo_desc" : "Titulo";

            if (busca != null)
            {
                itens.Where(i => i.Value == busca.ToString()).First().Selected = true;
            }
            if (busca == 1 && (!String.IsNullOrEmpty(search)))
            {
                var id = (from c in _context.Livro
                          where c.Titulo.Contains(search) &&
                          c.IdentityUserId == userId
                          select c.Id).ToList();

                foreach (var ids in id)
                {
                    var titulo = (from livro in _context.Livro
                                  where livro.Id == ids
                                  select livro.Titulo).FirstOrDefault();

                    var edicao = (from livro in _context.Livro
                                  where livro.Id == ids
                                  select livro.Edicao).FirstOrDefault();

                    var ano = (from livro in _context.Livro
                               where livro.Id == ids
                               select livro.Ano).FirstOrDefault();

                    var editora = (from livro in _context.Livro
                                   where livro.Id == ids
                                   select livro.Editora.Nome).FirstOrDefault();

                    var autores = (from autor in _context.Autor
                                   join livroAutor in _context.LivroAutor
                                   on autor.Id equals livroAutor.AutorId
                                   join livro in _context.Livro
                                   on livroAutor.LivroId equals livro.Id
                                   where livro.Id == ids
                                   select autor.Nome).ToList();

                    var assuntos = (from assunto in _context.Assunto
                                    join LivroAssunto in _context.LivroAssunto
                                    on assunto.Id equals LivroAssunto.AssuntoId
                                    join livro in _context.Livro
                                    on LivroAssunto.LivroId equals livro.Id
                                    where livro.Id == ids
                                    select assunto.Nome).ToList();

                    var foto = selecionarFoto(ids);

                    
                        Livro.Add(new Livros
                    {
                        Id = ids,
                        Titulo = titulo,
                        Edicao = edicao,
                        Ano = ano,
                        Editora = editora,
                        Autores = autores,
                        Assuntos = assuntos,
                        Foto = foto
                    });
                }
                ViewBag.Livro = Livro;
            }
            else if (busca == 2 && (!String.IsNullOrEmpty(search)))
            {
                var id = (from c in _context.Livro
                          join livroAutor in _context.LivroAutor
                          on c.Id equals livroAutor.LivroId
                          join autor in _context.Autor
                          on livroAutor.AutorId equals autor.Id
                          where autor.Nome.Contains(search) &&
                          c.IdentityUserId == userId
                          select c.Id).ToList();

                foreach (var ids in id)
                {
                    var titulo = (from livro in _context.Livro
                                  where livro.Id == ids
                                  select livro.Titulo).FirstOrDefault();

                    var edicao = (from livro in _context.Livro
                                  where livro.Id == ids
                                  select livro.Edicao).FirstOrDefault();

                    var ano = (from livro in _context.Livro
                               where livro.Id == ids
                               select livro.Ano).FirstOrDefault();

                    var editora = (from livro in _context.Livro
                                   where livro.Id == ids
                                   select livro.Editora.Nome).FirstOrDefault();

                    var autores = (from autor in _context.Autor
                                   join livroAutor in _context.LivroAutor
                                   on autor.Id equals livroAutor.AutorId
                                   join livro in _context.Livro
                                   on livroAutor.LivroId equals livro.Id
                                   where livro.Id == ids
                                   select autor.Nome).ToList();

                    var assuntos = (from assunto in _context.Assunto
                                    join LivroAssunto in _context.LivroAssunto
                                    on assunto.Id equals LivroAssunto.AssuntoId
                                    join livro in _context.Livro
                                    on LivroAssunto.LivroId equals livro.Id
                                    where livro.Id == ids
                                    select assunto.Nome).ToList();

                    var foto = selecionarFoto(ids);

                    Livro.Add(new Livros
                    {
                        Id = ids,
                        Titulo = titulo,
                        Edicao = edicao,
                        Ano = ano,
                        Editora = editora,
                        Autores = autores,
                        Assuntos = assuntos,
                        Foto = foto
                    });
                }
                ViewBag.Livro = Livro;
            }
            else if (busca == 3 && (!String.IsNullOrEmpty(search)))
            {
                var id = (from c in _context.Livro
                          join editora in _context.Editora
                          on c.EditoraId equals editora.Id
                          where editora.Nome.Contains(search) &&
                          c.IdentityUserId == userId
                          select c.Id).ToList();
                foreach (var ids in id)
                {
                    var titulo = (from livro in _context.Livro
                                  where livro.Id == ids
                                  select livro.Titulo).FirstOrDefault();

                    var edicao = (from livro in _context.Livro
                                  where livro.Id == ids
                                  select livro.Edicao).FirstOrDefault();

                    var ano = (from livro in _context.Livro
                               where livro.Id == ids
                               select livro.Ano).FirstOrDefault();

                    var editora = (from livro in _context.Livro
                                   where livro.Id == ids
                                   select livro.Editora.Nome).FirstOrDefault();

                    var autores = (from autor in _context.Autor
                                   join livroAutor in _context.LivroAutor
                                   on autor.Id equals livroAutor.AutorId
                                   join livro in _context.Livro
                                   on livroAutor.LivroId equals livro.Id
                                   where livro.Id == ids
                                   select autor.Nome).ToList();

                    var assuntos = (from assunto in _context.Assunto
                                    join LivroAssunto in _context.LivroAssunto
                                    on assunto.Id equals LivroAssunto.AssuntoId
                                    join livro in _context.Livro
                                    on LivroAssunto.LivroId equals livro.Id
                                    where livro.Id == ids
                                    select assunto.Nome).ToList();

                    var foto = selecionarFoto(ids);

                    Livro.Add(new Livros
                    {
                        Id = ids,
                        Titulo = titulo,
                        Edicao = edicao,
                        Ano = ano,
                        Editora = editora,
                        Autores = autores,
                        Assuntos = assuntos,
                        Foto = foto
                    });

Library/Views/Livros/Create.cshtml
@model Library.Models.ViewModels.LivroAutorAssunto

@{
    Layout = "_Layout";
    ViewData["Title"] = "Novo Livro";
    var jaExiste = ViewBag.JaExiste;
}

<h1>@ViewData["Title"]</h1>
<h5 class="text-danger">@jaExiste</h5>
<br>


<form asp-action="Create" asp-controller="livros" enctype="multipart/form-data" method="post">
    <div class="d-flex flex-column div-create justify-content-center">
        <div class="d-flex flex-row justify-content-start">
            <b>Capa</b>
            <input type="file" name="foto" class="input-add" />
        </div>
        <div class="d-flex flex-row justify-content-start">
            <b>   <label asp-for="Livro.Titulo"></label></b>
            <input asp-for="Livro.Titulo" class="input-add" />
            <span asp-validation-for="Livro.Titulo"></span>
        </div>
        <div class="d-flex flex-row justify-content-start">
            <b>  <label asp-for="Livro.Edicao"></label></b>
            <input asp-for="Livro.Edicao" class="input-add" />
            <span asp-validation-for="Livro.Edicao"></span>
        </div>
        <div class="d-flex flex-row justify-content-start">
            <b>  <label asp-for="Livro.Ano"></label></b>
            <input asp-for="Livro.Ano" class="input-add" />
            <span asp-validation-for="Livro.Ano"></span>
        </div>
        <div class="d-flex flex-row justify-content-start">
            <b> <label asp-for="Livro.Editora.Nome"></label></b>
            <input asp-for="Livro.Editora.Nome" class="input-add" />
            <span asp-validation-for="Livro.Editora"></span>
        </div>
        <div class="d-flex flex-row justify-content-start">
            <b><label asp-for="Assunto.Nome"></label></b>
            <select asp-for="Assunto.Nome" class="input-add" asp-items="ViewBag.LivroAssunto" id="assuntoAdicionado"></select>
            <input type="button" onclick="adicionarAssunto()" value="+" class="btn-add" />
            <a href="/Assuntos/Create" class="btn-assuntos">Assuntos &#10141;</a>
        </div>
        <ul id="assuntoLista">
        </ul>
        <div class="d-flex flex-row justify-content-start">
            <b> <label asp-for="Autor.Nome"></label></b>
            <input asp-for="Autor.Nome" class="input-add" id="autorAdicionado" />
            <input type="button" onclick="adicionarAutor()" value="+" class="btn-add" />
        </div>
        <ul id="autorLista">
        </ul>
        <div class="div-novo-livro">
            <input type="submit" value="Adicionar" class="novo-livro add-livro" onclick="validando()" />
        </div>
    </div>
</form>
<div class="voltar">
    <a asp-action="Index"> &larr; Voltar</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    var umAutor = true
    var umAssunto = true

    function adicionarAutor() {
        let autorAdicionado = document.getElementById('autorAdicionado').value
        let autorLista = document.getElementById('autorLista')
        let item = document.createElement('li')
        item.textContent = autorAdicionado

        let check = document.createElement('input')
        check.setAttribute('type', "checkbox")
        check.setAttribute('checked', "checked")
        check.setAttribute('name', "listaAutores")
        check.setAttribute('value', autorAdicionado)
        item.appendChild(check)
        autorLista.appendChild(item)

        umAutor = false
    }

    function validando() {
        if (umAutor) {
            let autorAdicionado = document.getElementById('autorAdicionado').value
            let autorLista = document.getElementById('autorLista')
            let item = document.createElement('li')
            item.textContent = autorAdicionado

            let check = document.createElement('input')
            check.setAttribute('type', "hidden")
            check.setAttribute('checked', "checked")
            check.setAttribute('name', "listaAutores")
            check.setAttribute('value', autorAdicionado)
            autorLista.appendChild(check)
        }

        if (umAssunto) {
            let assunto = document.getElementById('assuntoAdicionado').value
            let assuntoLista = document.getElementById('assuntoLista')
            let item = document.createElement('li')
            item.textContent = assunto

            let check = document.createElement('input')
            check.setAttribute('type', "hidden")
            check.setAttribute('checked', "checked")
            check.setAttribute('name', "listaAssuntos")
            check.setAttribute('value', assunto)
            assuntoLista.appendChild(check)
        }
    }

    function adicionarAssunto() {
        let assuntoAdicionado = document.getElementById('assuntoAdicionado').textContent
        let assuntoNum = document.getElementById('assuntoAdicionado').value

        let assuntoLista = document.getElementById('assuntoLista')
        let item = document.createElement('li')

        var assuntos = assuntoAdicionado.split(" ")

        for (var i = 0; i <= assuntos.length; i++) {
            switch (assuntoNum) {
                case i:
                    item.innerHTML = assuntos[i + 1]
                    break;
            }
        }

        let check = document.createElement('input')
        check.setAttribute('type', "checkbox")
        check.setAttribute('checked', "checked")
        check.setAttribute('name', "listaAssuntos")
        check.setAttribute('value', assuntoNum)
        item.appendChild(check)
        assuntoLista.appendChild(item)

        umAssunto = false
    }
</script>

Library/Views/Livros/Delete.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Deletar";
    var livro = ViewBag.Livro;
    var pev = "; ";
    var virg = ", ";
    int i = 0;
    int c = 0;
}
<br />
<h3 class="text-center">Tem certeza que deseja deletar esse livro?</h3>

<div class="d-flex flex-row flex-wrap livro-delete justify-content-center">
    <div class="d-flex">
        @foreach (var livros in livro)
        {
            @if (livros.Foto != null)
            {
                <div>
                    <img src="/Livros/selecionarFoto/@livros.Id" class="foto-delete" />
                </div>
            }
            else
            {
                <div class="text-center">
                    <img src="~/image/sem-foto.jpg" alt="Sem foto" class="foto" />
                </div>
            }

        }
        <br />
    </div>
    <div class="d-flex flex-column div-delete justify-content-between">
        <div>
            <div>
                <p>
                    <b>Título: </b>
                    @foreach (var titulo in livro)
                    {
                        @titulo.Titulo
                    }
                </p>
                <p>
                    <b>Autor:</b>
                    @foreach (var livros in livro)
                    {
                        @foreach (var autor in livros.Autores)
                        {
                            @autor
                            i++;
                            @if (i > 1)
                            {
                                @pev
                            }
                        }
                    }
                </p>
                <p>
                    <b>Edição: </b>
                    @foreach (var edicao in livro)
                    {
                        @edicao.Edicao
                    } ª edição
                </p>
                <p>
                    <b>Ano: </b>
                    @foreach (var ano in livro)
                    {
                        @ano.Ano
                    }
                </p>
                <p>
                    <b>Editora: </b>
                    @foreach (var editora in livro)
                    {
                        @editora.Editora
                    }
                </p>
                <p>
                    <b>Gênero: </b>
                    @foreach (var livros in livro)
                    {
                        @foreach (var assunto in livros.Assuntos)
                        {
                            @assunto
                            c++;
                            if (c > 1)
                            {
                                @virg
                            }
                        }
                    }
                </p>
            </div>
            <div>
            </div>
        </div>
    </div>
    </div>
    <div class="text-center mt-5">

        <form asp-action="Delete">
            @foreach (var livros in livro)
            {
                <input type="hidden" value="@livros.Id" name="id" />
            }
            <input type="submit" value="Deletar" class="btn btn-danger w-25" />
        </form>
    </div>

    <div class="voltar">
        <a asp-action="Index"> &larr; Voltar</a>
    </div>

Library/Views/Livros/Details.cshtml
@{
    Layout = "_Layout";
    var livro = ViewBag.Livro;
    var pev = "; ";
    var virg = ", ";
    int i = 0;
    int c = 0;
}
<br />
@foreach (var livros in livro)
{
    <h1 class="d-flex flex-row justify-content-center">
        @livros.Titulo
        <a asp-action="Edit" asp-route-id="@livros.Id">
            <img src="~/image/editar.png" alt="Editar" width="30" class="lixeira" />
        </a>
    </h1>
}

<div class="d-flex flex-row flex-wrap livro-delete justify-content-center">
    <div class="d-flex">
        @foreach (var livros in livro)
        {
            @if (livros.Foto != null)
            {
                <div>
                    <img src="/Livros/selecionarFoto/@livros.Id" class="foto-delete" />
                </div>
            }
            else
            {
                <div class="text-center">
                    <img src="~/image/sem-foto.jpg" alt="Sem foto" class="foto" />
                </div>
            }

        }
        <br />
    </div>
    <div class="d-flex flex-column div-delete justify-content-between">
        <div>
            <p>
                <b>Título: </b>
                @foreach (var titulo in livro)
                {
                    @titulo.Titulo
                }
            </p>
            <p>
                <b>Autor:</b>
                @foreach (var livros in livro)
                {
                    @foreach (var autor in livros.Autores)
                    {
                        @autor
                        i++;
                        @if (i > 1)
                        {
                            @pev
                        }
                    }
                }
            </p>
            <p>
                <b>Edição: </b>
                @foreach (var edicao in livro)
                {
                    @edicao.Edicao
                } ª edição
            </p>
            <p>
                <b>Ano: </b>
                @foreach (var ano in livro)
                {
                    @ano.Ano
                }
            </p>
            <p>
                <b>Editora: </b>
                @foreach (var editora in livro)
                {
                    @editora.Editora
                }
            </p>
            <p>
                <b>Gênero: </b>
                @foreach (var livros in livro)
                {
                    @foreach (var assunto in livros.Assuntos)
                    {
                        @assunto
                        c++;
                        if (c > 1)
                        {
                            @virg
                        }
                    }
                }
            </p>
        </div>
        <div>
        </div>
    </div>
</div>
<div class="voltar">
    <a asp-action="Index"> &larr; Voltar</a>
</div>

Library/Views/Livros/Edit.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Editar";
    var livro = ViewBag.Livro;
}

<h3>@ViewData["Title"]</h3>
<br />

<form asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="d-flex flex-column div-create justify-content-center">
        @foreach (var livros in livro)
        {<div class="d-flex flex-row justify-content-start">
                <b>Capa</b>
                <input type="file" name="foto" class="input-add" value="@livros.Foto" />
            </div>
            <input type="hidden" value="@livros.Id" name="id" />
            <div class="d-flex flex-row justify-content-start">
                <b>Título</b> <input type="text" name="titulo" value="@livros.Titulo" class="input-add" />
            </div>
            <div class="d-flex flex-row justify-content-start">
                <b>Edição</b> <input type="text" name="edicao" value="@livros.Edicao" class="input-add" />
            </div>
            <div class="d-flex flex-row justify-content-start">
                <b>Ano</b> <input type="text" name="ano" value="@livros.Ano" class="input-add" />
            </div>
            <div class="d-flex flex-row justify-content-start">
                <b>Editora</b> <input type="text" name="editora" value="@livros.Editora" class="input-add" />
            </div>

            @foreach (var assunto in ViewBag.Assunto)
            {
                <div class="d-flex flex-row justify-content-start">
                    <b>Assunto</b>
                    @Html.DropDownList("assuntos", (SelectList)assunto, new { @class = "input-add" })
                </div>
            }

            @foreach (var autores in livros.Autores)
            {
                <div class="d-flex flex-row justify-content-start">
                    <b>Autor</b> <input type="text" name="autores" value="@autores" class="input-add" />
                </div>
            }
        }
        <div class="div-novo-livro">
            <input type="submit" value="Salvar" class="novo-livro add-livro" />
        </div>
    </div>
</form>

<div class="voltar">
    <a asp-action="Index"> &larr; Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Livros/Index.cshtml
-@{
    Layout = "_Layout";
    ViewData["Title"] = "Minha Biblioteca";
    var livro = ViewBag.Livro;
    var pev = "...+";
    int i = 0;
}

<h1 class="roboto">
    @ViewData["Title"]
</h1>

<br />
<form asp-controller="Livros" asp-action="Index" method="get">
    <div class="d-flex flex-row">
        @Html.DropDownList("busca", null, new
        {
         onchange = "document.location.href='/livros/index?busca='+this.value;"
        })

        <input type="text" name="search" class="input-livro">
        <input type="submit" value="Pesquisar" class="button-livro" />
    </div>
</form>
<br />
<div class="ordenar d-flex flex-row justify-content-end">
 @Html.ActionLink("Título", "Index", new { order = ViewBag.Titulo }, new { @class="ordenar"})
  <div> &uarr;&darr; </div>  
</div>

<div class="container">
    <div class="row">
        @foreach (var item in livro)
        {
            <div class="col-12 col-sm-6 mt-5">
                <div class="d-flex flex-row">
                    <div class="div-foto">
                        @if (item.Foto != null)
                        {
                            <a asp-action="Details" asp-route-id="@item.Id">
                                <img src="/Livros/selecionarFoto/@item.Id" class="foto selecionar-livro" alt="Capa do livro" />
                            </a>
                        }
                        else
                        { <a asp-action="Details" asp-route-id="@item.Id">
                                <img src="~/image/sem-foto.jpg" class="foto selecionar-livro" alt="Sem foto" />
                            </a>
                        }
                    </div>
                    <div class="d-flex flex-column justify-content-between">
                        <div class="d-flex flex-row">
                            <div class="autor">
                                @foreach (var autores in item.Autores)
                                {
                                    i = 0;
                                }
                                @foreach (var autores in item.Autores)
                                {
                                    @if (i == 0)
                                    {
                                        @autores
                                    }
                                    @if (i == 1)
                                    {
                                        @pev
                                    }
                                    i++;
                                }
                            </div>
                            <div>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn edit">
                                    <img src="~/image/editar.png" alt="Editar" width="15" />
                                </a>
                            </div>
                        </div>
                        <div>
                            <h5 class="text-center title">@item.Titulo</h5>
                        </div>
                        <div class="d-flex flex-row">
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn-detalhes">
                                Detalhes
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.Id">
                                <img src="~/image/lixeira.png" alt="Lixeira" width="20" class="lixeira" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="div-novo-livro">
    <a asp-action="Create" class="novo-livro">Novo Livro</a>
</div>